<!DOCTYPE html>
<html>

<body style="font-family: Arial, sans-serif; margin: 0; padding: 0;">
    <table style="width: 100%; max-width: 600px; margin: 20px auto; border-collapse: collapse; background-color: #fff; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
        <tr>
            <td colspan="2" style="background-color: #4CAF50; color: white; padding: 10px; text-align: center;">
                <h3 style="margin: 0;">Reservation:</h3>
            </td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">Check in:</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                <?= $data['checkin']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">Check Out:</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                <?= $data['checkout']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">Phone Number:</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                <?= $data['phone']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">Number of Persons:</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                <?= $data['person']; ?>
            </td>
        </tr>
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">Email:</td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                <?= $data['email']; ?>
            </td>
        </tr>
    </table>
</body>

</html>
